-- Add short_id columns to spaces and scenes for URL-friendly identifiers.
-- Uses 10-char alphanumeric IDs (base62) generated by application code.
-- This migration backfills existing rows with random short IDs.

CREATE OR REPLACE FUNCTION generate_short_id(length int DEFAULT 10)
RETURNS text AS $$
DECLARE
  chars text := '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  result text := '';
  i int;
BEGIN
  FOR i IN 1..length LOOP
    result := result || substr(chars, floor(random() * 62 + 1)::int, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- spaces.short_id
ALTER TABLE public.spaces ADD COLUMN IF NOT EXISTS short_id text;
UPDATE public.spaces SET short_id = generate_short_id(10) WHERE short_id IS NULL;
ALTER TABLE public.spaces ALTER COLUMN short_id SET NOT NULL;
ALTER TABLE public.spaces ADD CONSTRAINT spaces_short_id_unique UNIQUE (short_id);
CREATE INDEX IF NOT EXISTS idx_spaces_short_id ON public.spaces(short_id);

-- scenes.short_id
ALTER TABLE public.scenes ADD COLUMN IF NOT EXISTS short_id text;
UPDATE public.scenes SET short_id = generate_short_id(10) WHERE short_id IS NULL;
ALTER TABLE public.scenes ALTER COLUMN short_id SET NOT NULL;
ALTER TABLE public.scenes ADD CONSTRAINT scenes_short_id_unique UNIQUE (short_id);
CREATE INDEX IF NOT EXISTS idx_scenes_short_id ON public.scenes(short_id);
